-- Disable RLS temporarily to allow truncation
ALTER TABLE videos DISABLE ROW LEVEL SECURITY;
ALTER TABLE categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE cast_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE video_categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE video_cast DISABLE ROW LEVEL SECURITY;
ALTER TABLE video_ratings DISABLE ROW LEVEL SECURITY;
ALTER TABLE video_bookmarks DISABLE ROW LEVEL SECURITY;
ALTER TABLE watch_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE comments DISABLE ROW LEVEL SECURITY;
ALTER TABLE comment_votes DISABLE ROW LEVEL SECURITY;

-- Truncate all tables with CASCADE to handle foreign keys
TRUNCATE TABLE comment_votes CASCADE;
TRUNCATE TABLE comments CASCADE;
TRUNCATE TABLE watch_history CASCADE;
TRUNCATE TABLE video_bookmarks CASCADE;
TRUNCATE TABLE video_ratings CASCADE;
TRUNCATE TABLE video_cast CASCADE;
TRUNCATE TABLE video_categories CASCADE;
TRUNCATE TABLE videos CASCADE;
TRUNCATE TABLE cast_members CASCADE;
TRUNCATE TABLE categories CASCADE;

-- Re-enable RLS
ALTER TABLE videos ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE cast_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE video_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE video_cast ENABLE ROW LEVEL SECURITY;
ALTER TABLE video_ratings ENABLE ROW LEVEL SECURITY;
ALTER TABLE video_bookmarks ENABLE ROW LEVEL SECURITY;
ALTER TABLE watch_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE comment_votes ENABLE ROW LEVEL SECURITY;
