-- Disable RLS temporarily to ensure truncation works
ALTER TABLE comment_votes DISABLE ROW LEVEL SECURITY;
ALTER TABLE comments DISABLE ROW LEVEL SECURITY;
ALTER TABLE watch_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE video_bookmarks DISABLE ROW LEVEL SECURITY;
ALTER TABLE video_ratings DISABLE ROW LEVEL SECURITY;
ALTER TABLE video_cast DISABLE ROW LEVEL SECURITY;
ALTER TABLE video_categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE videos DISABLE ROW LEVEL SECURITY;
ALTER TABLE cast_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE scraper_failed DISABLE ROW LEVEL SECURITY;
ALTER TABLE scraper_pending DISABLE ROW LEVEL SECURITY;
ALTER TABLE scraper_completed DISABLE ROW LEVEL SECURITY;
ALTER TABLE scraper_progress DISABLE ROW LEVEL SECURITY;
ALTER TABLE scraper_random_state DISABLE ROW LEVEL SECURITY;

-- Delete all data
DELETE FROM comment_votes;
DELETE FROM comments;
DELETE FROM watch_history;
DELETE FROM video_bookmarks;
DELETE FROM video_ratings;
DELETE FROM video_cast;
DELETE FROM video_categories;
DELETE FROM videos;
DELETE FROM cast_members;
DELETE FROM categories;
DELETE FROM scraper_failed;
DELETE FROM scraper_pending;
DELETE FROM scraper_completed;
DELETE FROM scraper_progress;
DELETE FROM scraper_random_state;

-- Re-enable RLS
ALTER TABLE comment_votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE watch_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE video_bookmarks ENABLE ROW LEVEL SECURITY;
ALTER TABLE video_ratings ENABLE ROW LEVEL SECURITY;
ALTER TABLE video_cast ENABLE ROW LEVEL SECURITY;
ALTER TABLE video_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE videos ENABLE ROW LEVEL SECURITY;
ALTER TABLE cast_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE scraper_failed ENABLE ROW LEVEL SECURITY;
ALTER TABLE scraper_pending ENABLE ROW LEVEL SECURITY;
ALTER TABLE scraper_completed ENABLE ROW LEVEL SECURITY;
ALTER TABLE scraper_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE scraper_random_state ENABLE ROW LEVEL SECURITY;
